In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [8]:
df=pd.read_excel(r"C:\Users\Gnanajothi.M\OneDrive\Desktop\Spotify Song Trends and Audio Feature Analysis\dataset\spotify_songs.xlsx",header=None)

In [15]:
spotify=pd.read_excel(r"C:\Users\Gnanajothi.M\OneDrive\Desktop\Spotify Song Trends and Audio Feature Analysis\dataset\spotify_songs.xlsx")

In [16]:
spotify.head()

,track_id,track_name,track_artist,lyrics,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,language
0,0017A6SJgTbfQVU2EtsPNo,Pangarap,Barbie's Cradle,Minsan pa Nang ako'y napalingon Hindi ko alam ...,41,1srJQ0njEQgd8w4XSqI4JQ,Trip,2001-01-01 00:00:00,Pinoy Classic Rock,37i9dQZF1DWYDQ8wBxd7xt,...,-10.068,1,0.0236,0.27900,0.01170,0.0887,0.566,97.091,235440,tl
1,004s3t0ONYlzxII9PLgU6z,I Feel Alive,Steady Rollin,"The trees, are singing in the wind The sky blu...",28,3z04Lb9Dsilqw68SHt6jLB,Love & Loss,2017-11-21 00:00:00,Hard Rock Workout,3YouF0u7waJnolytf9JCXf,...,-4.739,1,0.0442,0.01170,0.00994,0.3470,0.404,135.225,373512,en
2,00chLpzhgVjxs1zKC9UScL,Poison,Bell Biv DeVoe,"NA Yeah, Spyderman and Freeze in full effect U...",0,6oZ6brjB8x3GoeSYdwJdPc,Gold,2005-01-01 00:00:00,"Back in the day - R&B, New Jack Swing, Swingbe...",3a9y4eeCJRmG9p4YKfqYIx,...,-7.504,0,0.2160,0.00432,0.00723,0.4890,0.650,111.904,262467,en
3,00cqd6ZsSkLZqGMlQCR0Zo,Baby It's Cold Outside (feat. Christina Aguilera),CeeLo Green,I really can't stay Baby it's cold outside I'v...,41,3ssspRe42CXkhPxdc12xcp,CeeLo's Magic Moment,2012-10-29 00:00:00,Christmas Soul,6FZYc2BvF7tColxO8PBShV,...,-5.819,0,0.0341,0.68900,0.00000,0.0664,0.405,118.593,243067,en
4,00emjlCv9azBN0fzuuyLqy,Dumb Litty,KARD,Get up out of my business You don't keep me fr...,65,7h5X3xhh3peIK9Y0qI5hbK,KARD 2nd Digital Single â€˜Dumb Littyâ€™,2019-09-22 00:00:00,K-Party Dance Mix,37i9dQZF1DX4RDXswvP6Mj,...,-1.993,1,0.0409,0.03700,0.00000,0.1380,0.240,130.018,193160,en

In [17]:
spotify.tail()

,track_id,track_name,track_artist,lyrics,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,language
18449,7zXzWCVuz7whIuYZyEAlxt,Rising Like The Sun - Radio Mix,Qulinez,"Caught up in such a head rush, wide-eyed latel...",0,1l4aoukbPgi5u2OaE2R4Zj,Rising Like The Sun,2014-03-24 00:00:00,â™¥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,...,-5.778,0,0.0878,0.00555,0.000000,0.335,0.211,128.012,208656,en
18450,7zycSpvjDcqh6YT1FEl2kY,Anaconda,Nicki Minaj,"My anaconda don't, my anaconda don't My anacon...",49,5qs8T6ZHSrnllnOuUk6muC,The Pinkprint (Deluxe Edition),2014-12-15 00:00:00,10er Playlist,1kEczIkZH8IgaWT2BiApxZ,...,-6.224,1,0.1800,0.06730,0.000006,0.214,0.647,129.990,260240,en
18451,7zye9v6B785eFWEFYs13C2,Bound,Ponderosa Twins Plus One,"Bound, bound Bound, bound Bound to fall in lov...",40,1xdgLmTFMSyJyI5DJOOX7T,2+2+1 = (Digitally Remastered),2013-07-09 00:00:00,Sexy Soul 2020,5EMARioe9z9eKOeWIAC2JW,...,-6.457,0,0.0270,0.71500,0.000428,0.115,0.657,142.218,191205,en
18452,7zyLObYw4QUKQDyZOb4J0Y,I'll Do 4 U (Re-Recorded / Remastered),Father MC,(Would you do for me) Sweetheart (Would you do...,36,14HYMxFhpgDIr9cci1u0kt,I'll Do 4 U (Re-Recorded / Remastered),2010-10-01 00:00:00,New Jack Swing/ R&B Hits: 1987 - 2002,4sji14lrB5bgcr51lPALYH,...,-4.920,0,0.0633,0.14300,0.000000,0.072,0.810,109.536,223890,en
18453,7zzZmpw8L66ZPjH1M6qmOs,Migraine,Moonstar88,"Oo nga pala, hindi nga pala tayo Hanggang dito...",61,4t3FtECyV1gClHmpBhXSfB,When I Met You,2008-07-28 00:00:00,Pinoy Classic Rock,37i9dQZF1DWYDQ8wBxd7xt,...,-6.000,1,0.0290,0.21700,0.000003,0.118,0.221,115.049,267960,tl

In [19]:
spotify.sample(5)

,track_id,track_name,track_artist,lyrics,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,language
7976,3gMJMSrU2QETbsILNuybIh,Make A Move - Pt. 2,EMMA WAHLIN,Been feeling like I'm all alone Just wanna fin...,17,5Z1moi6b6T4njtHjepFZ9q,Make A Move (Pt. 2),2020-01-17 00:00:00,Dance Pop: Japan,37i9dQZF1DXahYFr91pFvG,...,-7.575,0,0.1400,0.617,0.018200,0.1840,0.463,123.972,181200,en
12360,5CE1jL4dkfZlX5CiHZh5ap,No Romeo No Juliet,50 Cent,"Ayo, quit Captain Savin', serenadin' them hoes...",59,1TfWU86ZevMnfkHcEHCbyA,No Romeo No Juliet,2016-05-11 00:00:00,Gangsta Rap/90's Hip-Hop,39IFMVQdRNdb7kVfyTvHjM,...,-5.643,0,0.2190,0.341,0.000000,0.0578,0.394,120.073,268487,en
1439,0nyrltZrQGAJMBZc1bYvuQ,Get Up Offa That Thing,James Brown,Aaaaaaaaaaaaaaaaaaaw!!! Oh! Say it now!I'm bac...,53,6MjOv3BeIjmht2ymtRih3s,20 All-Time Greatest Hits!,1991,The 1950s/1960s/1970s/1980s/1990s/2000s/2010s ...,1S7BckuYIkEazeNKOSM0uA,...,-10.395,1,0.4110,0.225,0.000002,0.9410,0.800,118.104,250200,en
11504,4vSQiyuTOUHvKM043BGqa4,Eu Tenho Drip,Derek,"NA Hol up, hol up Hol up, hol up, hol up Hol u...",57,4iEIIZm3DWbsqcJ0oxSEa8,Eu Tenho Drip,2019-10-04 00:00:00,Trap Ouro,37i9dQZF1DWYBXtbGSCurj,...,-10.136,1,0.0720,0.251,0.000014,0.4970,0.479,122.000,99605,pt
5102,28WbijaWIjv7D6D4qVIcYQ,Axolotl,The Veils,"I'm glowing bright, obsidian Axolotl amphibian...",33,6gASlHZuvLvUUQymZHZGTX,Total Depravity,2016-08-26 00:00:00,Permanent Wave,5Go0Jsxj1UnsU7Om841BEo,...,-6.968,0,0.0559,0.218,0.624000,0.1100,0.163,96.037,183600,en

In [20]:
type(spotify)

pandas.DataFrame

In [21]:
spotify.shape

(18454, 25)

In [22]:
spotify.columns

Index(['track_id', 'track_name', 'track_artist', 'lyrics', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms', 'language'],
      dtype='str')

In [23]:
spotify.info()

<class 'pandas.DataFrame'>
RangeIndex: 18454 entries, 0 to 18453
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  18454 non-null  str
 1   track_name                18454 non-null  object
 2   track_artist              18454 non-null  object
 3   lyrics                    18194 non-null  str
 4   track_popularity          18454 non-null  int64
 5   track_album_id            18454 non-null  str
 6   track_album_name          18454 non-null  object
 7   track_album_release_date  18454 non-null  object
 8   playlist_name             18454 non-null  str
 9   playlist_id               18454 non-null  str
 10  playlist_genre            18454 non-null  str
 11  playlist_subgenre         18454 non-null  str
 12  danceability              18454 non-null  float64
 13  energy                    18454 non-null  float64
 14  key                       18454 non-null  int64
 15  loudness                  18454 non-null  float64
 16  mode                      18454 non-null  int64
 17  speechiness               18454 non-null  float64
 18  acousticness              18454 non-null  float64
 19  instrumentalness          18454 non-null  float64
 20  liveness                  18454 non-null  float64
 21  valence                   18454 non-null  float64
 22  tempo                     18454 non-null  float64
 23  duration_ms               18454 non-null  int64
 24  language                  18194 non-null  str
dtypes: float64(9), int64(4), object(4), str(8)
memory usage: 3.5+ MB

In [24]:
spotify.describe()

,track_popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
count,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000,18454.000000
mean,42.438821,0.644066,0.692289,5.342094,-6.769159,0.580525,0.106192,0.175348,0.051216,0.189593,0.520598,120.812167,230319.306763
std,24.616740,0.150071,0.180635,3.613121,2.920757,0.493487,0.102291,0.217795,0.168263,0.153751,0.228716,27.586424,57255.086685
min,0.000000,0.098500,0.016700,0.000000,-34.283000,0.000000,0.022400,0.000001,0.000000,0.009360,0.000010,37.114000,31893.000000
25%,24.000000,0.546000,0.573000,2.000000,-8.249000,0.000000,0.039700,0.016100,0.000000,0.092700,0.345000,98.856000,193230.250000
50%,48.000000,0.660000,0.715000,6.000000,-6.227000,1.000000,0.060300,0.081900,0.000009,0.128000,0.522000,120.045000,221340.000000
75%,62.000000,0.755000,0.835000,9.000000,-4.719000,1.000000,0.130000,0.254000,0.001720,0.246000,0.700000,135.984000,258078.250000
max,100.000000,0.979000,1.000000,11.000000,1.275000,1.000000,0.918000,0.992000,0.987000,0.996000,0.991000,214.047000,517810.000000

In [ ]:
spotify.isnull()

,track_id,track_name,track_artist,lyrics,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,language
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18449,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18450,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18451,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18452,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18453,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [36]:
spotify.isnull().sum()

track_id                    0
track_name                  0
track_artist                0
lyrics                      0
track_popularity            0
track_album_id              0
track_album_name            0
track_album_release_date    0
playlist_name               0
playlist_id                 0
playlist_genre              0
playlist_subgenre           0
danceability                0
energy                      0
key                         0
loudness                    0
mode                        0
speechiness                 0
acousticness                0
instrumentalness            0
liveness                    0
valence                     0
tempo                       0
duration_ms                 0
language                    0
dtype: int64

In [27]:
spotify.isnull().any(axis=1)

0        False
1        False
2        False
3        False
4        False
         ...
18449    False
18450    False
18451    False
18452    False
18453    False
Length: 18454, dtype: bool

In [28]:
spotify.isnull().all()

track_id                    False
track_name                  False
track_artist                False
lyrics                      False
track_popularity            False
track_album_id              False
track_album_name            False
track_album_release_date    False
playlist_name               False
playlist_id                 False
playlist_genre              False
playlist_subgenre           False
danceability                False
energy                      False
key                         False
loudness                    False
mode                        False
speechiness                 False
acousticness                False
instrumentalness            False
liveness                    False
valence                     False
tempo                       False
duration_ms                 False
language                    False
dtype: bool

In [34]:
spotify[spotify.isnull().any(axis=1)]

Empty DataFrame
Columns: [track_id, track_name, track_artist, lyrics, track_popularity, track_album_id, track_album_name, track_album_release_date, playlist_name, playlist_id, playlist_genre, playlist_subgenre, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, language]
Index: []

[0 rows x 25 columns]

In [32]:
spotify["lyrics"] = spotify["lyrics"].fillna("Unknown")

In [33]:
spotify["language"] = spotify["language"].fillna("Unknown")

In [35]:
spotify.info()

<class 'pandas.DataFrame'>
RangeIndex: 18454 entries, 0 to 18453
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  18454 non-null  str
 1   track_name                18454 non-null  object
 2   track_artist              18454 non-null  object
 3   lyrics                    18454 non-null  str
 4   track_popularity          18454 non-null  int64
 5   track_album_id            18454 non-null  str
 6   track_album_name          18454 non-null  object
 7   track_album_release_date  18454 non-null  object
 8   playlist_name             18454 non-null  str
 9   playlist_id               18454 non-null  str
 10  playlist_genre            18454 non-null  str
 11  playlist_subgenre         18454 non-null  str
 12  danceability              18454 non-null  float64
 13  energy                    18454 non-null  float64
 14  key                       18454 non-null  int64
 15  loudness                  18454 non-null  float64
 16  mode                      18454 non-null  int64
 17  speechiness               18454 non-null  float64
 18  acousticness              18454 non-null  float64
 19  instrumentalness          18454 non-null  float64
 20  liveness                  18454 non-null  float64
 21  valence                   18454 non-null  float64
 22  tempo                     18454 non-null  float64
 23  duration_ms               18454 non-null  int64
 24  language                  18454 non-null  str
dtypes: float64(9), int64(4), object(4), str(8)
memory usage: 3.5+ MB

In [37]:
spotify.shape

(18454, 25)

In [38]:
spotify.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18449    False
18450    False
18451    False
18452    False
18453    False
Length: 18454, dtype: bool

In [39]:
spotify.duplicated().sum()

np.int64(0)